import fs from "fs";
import { Readable } from "stream";
import formidable from "formidable";
import { addCustomerQueue } from './queue.js'
import path from 'path';

export { handleUpload, streamArrayToClient, receiveArrayFromClient, tempReceiveArray }


function streamArrayToClient(res, array) {
  const jsonString = JSON.stringify(array);
  const buffer = Buffer.from(jsonString, "utf-8");
  const readable = new Readable();

  readable._read = () => { };
  readable.push(buffer);
  readable.push(null);

  res.writeHead(200, {
    "Content-Type": "application/json",
    "Content-Length": buffer.length,
  });
  readable.pipe(res);
}


async function tempReceiveArray(req, res) {
  let body = "";
  req.on("data", (chunk) => {
    body += chunk.toString();
  });
  req.on("end", () => {
    try {
      let data = JSON.parse(body);
      console.log(data);
      res.writeHead(204);
    } catch (err) {
      console.error(err);
      res.writeHead(400);
    }
  });
}

function receiveArrayFromClient(req, res)
{
  const readable = new Readable({
    read() {}
  });

  let chunks = [];
  let totalLength = 0;

  req.on('data', chunk => {
    chunks.push(chunk);
    totalLength += chunk.length;

    if (totalLength > 10000000) { 
      res.writeHead(413, {'Content-Type': 'text/plain'}).end('Request Entity Too Large');
      req.destroy();
      readable.destroy();
    }
  });

  req.on('end', () => {
    const json = Buffer.concat(chunks, totalLength).toString('utf-8');
    const array = JSON.parse(json);

    console.log("received following array:" + array);

    res.writeHead(204);
    res.end();

    return array;
  });

  req.on('error', error => {
    console.error('Error while handling sort request:', error);
    res.writeHead(500, {'Content-Type': 'text/plain'}).end('Internal Server Error');
  });

  readable.pipe(req);
}

async function handleUpload(form, req, user) { 
  try {
    const uploadedFile = await downloadFile(form, req);
    addCustomerQueue(user, uploadedFile);
  }
  catch {
    throw (422) //Unprocessable Entity
  }
}

async function downloadFile(form, req) {
  return new Promise((resolve, reject) => {
    form.parse(req, function (error, fields, file) {
      if (error) {
        console.error(error);
        reject(error);
      }

      if (!file.fileupload || !file.fileupload.filepath) {
        console.error("No file found");
        reject(new Error("No file found"));
        return;
      }

      const oldPath = file.fileupload.filepath;
      const ext = path.extname(file.fileupload.originalFilename).toLowerCase();
      //console.log(file.fileupload.originalFilename)
      if (ext !== ".csv") {
        console.error("Unexpected file type");
        reject(new Error(`Unexpected file type: ${ext}`));
        return;
      }

      const newPath = "./master/autogeneratedFiles/csvFiles/" + file.fileupload.originalFilename;

      // Create a read stream to stream the file directly to disk
      const readStream = fs.createReadStream(oldPath);
      const writeStream = fs.createWriteStream(newPath);

      // Pipe the read stream to the write stream to write the file to disk
      readStream.pipe(writeStream);

      // Remove the temporary file created by formidable
      readStream.on("end", function () {
        fs.unlinkSync(oldPath);

        // Check the file extension
        const ext = path.extname(newPath).toLowerCase();
        resolve(file.fileupload.originalFilename);

      });
    });
  });
}