import fs from "fs";
import { Readable } from "stream";
import formidable from "formidable";
import { addCustomerQueue } from './queue.js'
import path from 'path';

export { handleUpload, streamArrayToClient, receiveArrayFromClient }

function streamArrayToClient(res, array) {

  const readable = new Readable();

  const buffer = Buffer.from(array.buffer); 

  readable._read = () => { };
  readable.push(buffer);
  readable.push(null);

  res.writeHead(200, {
    "Content-Type": "application/octet-stream",
    "Content-Length": buffer.length,
  });

  readable.pipe(res);

}

async function receiveArray(req) {
  return new Promise((resolve) => {
    const chunks = [];

    req.on('data', chunk => {
      chunks.push(chunk);
    });

    req.on('end', () => {
      // Concatenate the received chunks into a single Buffer
      const buffer = Buffer.concat(chunks);

      // Create a UInt32Array from the Buffer
      const uint32Array = new Uint32Array(buffer.buffer, buffer.byteOffset, buffer.byteLength / Uint32Array.BYTES_PER_ELEMENT);

      // Resolve the promise with the UInt32Array
      resolve(uint32Array);
    });
  });
}

async function receiveArrayFromClient(req, res) {
  const result = await receiveArray(req);
  console.log(result);

  res.statusCode = 200;
  res.end();
  return result;
}

async function handleUpload(form, req, user) { 
  try {
    const uploadedFile = await downloadFile(form, req);
    addCustomerQueue(user, uploadedFile);
  }
  catch {
    throw (422) //Unprocessable Entity
  }
}

async function downloadFile(form, req) {
  return new Promise((resolve, reject) => {
    form.parse(req, function (error, fields, file) {
      if (error) {
        console.error(error);
        reject(error);
      }

      if (!file.fileupload || !file.fileupload.filepath) {
        console.error("No file found");
        reject(new Error("No file found"));
        return;
      }

      const oldPath = file.fileupload.filepath;
      const ext = path.extname(file.fileupload.originalFilename).toLowerCase();
      //console.log(file.fileupload.originalFilename)
      if (ext !== ".csv") {
        console.error("Unexpected file type");
        reject(new Error(`Unexpected file type: ${ext}`));
        return;
      }

      const newPath = "./master/autogeneratedFiles/csvFiles/" + file.fileupload.originalFilename;

      // Create a read stream to stream the file directly to disk
      const readStream = fs.createReadStream(oldPath);
      const writeStream = fs.createWriteStream(newPath);

      // Pipe the read stream to the write stream to write the file to disk
      readStream.pipe(writeStream);

      // Remove the temporary file created by formidable
      readStream.on("end", function () {
        fs.unlinkSync(oldPath);

        // Check the file extension
        const ext = path.extname(newPath).toLowerCase();
        resolve(file.fileupload.originalFilename);

      });
    });
  });
}